### ISSUE TITLE
Can't run the Eushully editor

### ISSUE THREAD

**Issue by marcussacana** [andreili/Eushully-Editor#7]
i tried run The Eushully editor but only show this error
![iwh1thz 1](https://cloud.githubusercontent.com/assets/10576957/7169828/6ad849b4-e39f-11e4-80c4-99a80a9ab14a.png)

i don't know japanese... this is a bug on my computer.. i use the 'unpacked_binaries' in this git... if this binaries is only for sample you can compile for me?

**Comment by andreili** [comment]
The program does not contain any text in Japanese, only in Russian. Perhaps the reason the system locale.
This program does not have full functionality, as I began to changed it in C ++ using Qt - mainly I work in Linux environment, so this variants to me preferable.
Added to the repository project on Qt, which at the moment is more functional and has hope for further development.
If you are interested in this project, please contact me via Skype: andreil499.
The program currently does not develop because of the lack of interest in its development.

**Comment by marcussacana** [comment]
Srry, i thought that this AGE is the Eussuly editor compiled... i view later kkkkkk
for this project.. i don't know pascal :/ but i need the tool to translate the kamidori... i say with the seisha translation but I was ignored... :/

**Comment by andreili** [comment]
The new version is more functional, written in C ++. But even there, there is no file editing - I have a problem with the file format (it is very complex and has many links inside).

**Comment by marcussacana** [comment]
i send a requet on skype for you

**Comment by marcussacana** [comment]
i make my own tool, after months...
url: https://github.com/marcussacana/EushullyEditor
